#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=03:00:00
#PBS -l vmem=30gb

#parse config.json for input parameters 
t1=$(jq -r .t1 config.json)
t2=$(jq -r .t2 config.json)
atlas=$(jq -r .atlas config.json)

# Run ashs segmentation, providing the t1, t2, and atlas paths
#ashs-fastashs_beta/bin/ashs_main.sh -I subj001 -a $atlas -g $t1 -f $t2 -w output/
if [ $atlas -eq "atlas1" ]; then
	singularity exec docker://brainlife/ashs:v1_atlas1 ./ashs_main.sh -a /atlas -g $t1 -f $t2 -w output/
fi
if [ $atlas -eq "atlas2" ]; then
	singularity exec docker://brainlife/ashs:v1_atlas2 ./ashs_main.sh -a /atlas -g $t1 -f $t2 -w output/
fi
# Check for output.
#[ ! -s track.tck ] && exit 1
