#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=03:00:00
#PBS -l vmem=30gb

#parse config.json for input parameters 
t1=$(jq -r .t1 config.json)
t2=$(jq -r .t2 config.json)
atlas=$(jq -r .atlas config.json)

# Run ashs segmentation, providing the t1, t2, and atlas paths
# ashs-fastashs_beta/bin/ashs_main.sh -I subj001 -a $atlas -g $t1 -f $t2 -w output/


# Select requested atlas.
#if [ "$atlas" == "Magdeburg-7t" ]; then
#	singularity exec docker://brainlife/ashs-upennpmc:2.0.0 ashs_main.sh -a /atlas -g $t1 -f $t2 -w output/
#fi
#if [ "$atlas" == "UMC-Utrecht-7t" ]; then
#	singularity exec docker://brainlife/ashs-upennpmc:2.0.0 ashs_main.sh -a /atlas -g $t1 -f $t2 -w output/
#fi
#if [ "$atlas" == "ASHS-separated-3t" ]; then
#	singularity exec docker://brainlife/ashs-upennpmc:2.0.0 ashs_main.sh -a /atlas -g $t1 -f $t2 -w output/
#fi
if [ "$atlas" == "ASHS-combined-3t" ]; then
	singularity exec docker://brainlife/ashs-ca23_combined:2.0.0 ashs_main.sh -a /atlas -g $t1 -f $t2 -w output/
fi
if [ "$atlas" == "Penntle" ]; then
	singularity exec docker://brainlife/ashs-penntle_hippo:2.0.0 ashs_main.sh -a /atlas -g $t1 -f $t2 -w output/
fi
#if [ "$atlas" == "Princeton-3t" ]; then
#	singularity exec docker://brainlife/ashs-upennpmc:2.0.0 ashs_main.sh -a /atlas -g $t1 -f $t2 -w output/
#fi
if [ "$atlas" == "UPENN-PMC-3t" ]; then
	singularity exec docker://brainlife/ashs-upennpmc:2.0.0 ashs_main.sh -a /atlas -g $t1 -f $t2 -w output/
fi

